apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: recommendations-cd
spec:
  description: |
    Initial CI/CD pipeline skeleton for the Recommendations service
  params:
    - default: 'https://github.com/CSCI-GA-2820-FA25-003/recommendations.git'
      description: URL to the git repo
      name: GIT_REPO
      type: string
    - default: master
      description: the reference (branch or ref)
      name: GIT_REF
      type: string
    - default: recommendations
      description: Name of the application
      name: APP_NAME
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.APP_NAME):latest'
      description: The name of image to build
      name: IMAGE_NAME
      type: string
#################################################
#               task1: git-clone                #
#################################################
  tasks:
    - name: git-clone
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: ''
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: 'true'
        - name: URL
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REF)
        - name: REFSPEC
          value: ''
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ''
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: output
          workspace: pipeline-workspace
#################################################
#               task2-1: pylint                 #
#################################################
    - name: pylint
      params:
        - name: image
          value: 'quay.io/rofrano/python:3.11-slim'
        - name: path
          value: service
        - name: args
          value: []
        - name: requirements-file
          value: requirements.txt
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: pylint
      workspaces:
        - name: source
          workspace: pipeline-workspace
#################################################
#               task2-2: pytest                 #
#################################################
    - name: pytest
      params:
        - name: pytest-args
          value: []
        - name: secret-name
          value: db-secret
        - name: secret-key
          value: DATABASE_URI
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: pytest-env
      workspaces:
        - name: source
          workspace: pipeline-workspace
#################################################
#               task3: buildah                  #
#################################################
    - name: buildah
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: DOCKERFILE
          value: .devcontainer/Dockerfile
        - name: CONTEXT
          value: .
        - name: STORAGE_DRIVER
          value: vfs
        - name: FORMAT
          value: oci
        - name: TLS_VERIFY
          value: "true"
      runAfter:
        - pylint
        - pytest
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: source
          workspace: pipeline-workspace
#################################################
#               task4: deploy image             #
#################################################
    - name: deploy-image
      params:
        - name: image-name
          value: $(params.IMAGE_NAME)
        - name: manifest-dir
          value: k8s
      runAfter:
        - buildah
      taskRef:
        kind: Task
        name: deploy-image
      workspaces:
        - name: source
          workspace: pipeline-workspace

#################################################
#               task5: behave                   #
#################################################
  workspaces:
    - name: pipeline-workspace
