apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: recommendations-cd
  namespace: XXXXXXX-dev # change namespace here !!!
spec:
  description: >
    Initial CI/CD pipeline skeleton for the Recommendations service
  workspaces:
    - name: pipeline-workspace 
  params:
    - name: git-repo
      type: string
      description: URL to the git repo
      default: https://github.com/CSCI-GA-2820-FA25-003/recommendations.git
    - name: git-ref
      type: string
      description: the reference (branch or ref)
      default: master          

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone        
      workspaces:
        - name: output
          workspace: pipeline-workspace 
      params:
        - name: url
          value: $(params.git-repo)
        - name: revision
          value: $(params.git-ref)
